### ISSUE TITLE
cannot add package

### ISSUE THREAD

**Issue by hans2103** [perfectwebteam/optimised-svgs#1]
Ik krijg een foutmelding bij installatie van deze package via yarn

> error Can't add "optimised-svgs": invalid package version "v1.0".

**Comment by robinpoort** [comment]
Kan je v2 proberen? https://github.com/perfectwebteam/optimised-svgs/releases/tag/v2.0.0

**Comment by hans2103** [comment]
@robinpoort v2.0.0 levert geen foutmelding op bij installatie.
